### ISSUE TITLE
kullanılan mekanizmayı readme de yazabilir misiniz? 

### ISSUE THREAD

**Issue by bbilginn** [ardamavi/Dog-Cat-Classifier#1]

**Comment by ardamavi** [comment]
Projeyi bitirdikten sonra tüm detaylarıyla dökümantasyon oluşturacağım.
Kodların açıklamalarından kullanılan mimariye kadar tüm detaylarıyla.

**Comment by ardamavi** [comment]
README.md dosyasını doldurdum.
